"""
Django settings for fizzingwhizzbee project.

Generated by 'django-admin startproject' using Django 3.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Set up environment variables
env = environ.Env()
environ.Env.read_env()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # my apps
    'apps.categories',
    'apps.merchants',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fizzingwhizzbee.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fizzingwhizzbee.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'fizzing_whizzbee',
        'USER': env('DATABASE_USER'),
        'PASSWORD': env('DATABASE_PASS'),
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


FEED_DATA = {
    'file_dir': BASE_DIR / 'files'
}

PROVIDERS = {
    'awin': {
        'api_key': 'd017bc3d12b35fc2455823e5ba4fc3a2',
        'merchants_endpoint': 'https://productdata.awin.com/datafeed/list/apikey/',
    },
    'kelkoo': {
        'api_key': 'eyJraWQiOiJkYWMwNjQzYy05ZmY2LTRmZTMtODFiMC1kNWYzZWNlYzYxMGEiLCJhbGciOiJSUzUxMiJ9.eyJzdWIiOiJwbXdzLWFwcGxpY2F0aW9uLWlkOjk3MSIsImF6cCI6IlNob3BwaW5nQVBJIiwiaXNzIjoiS2Vsa29vIEdyb3VwIiwiaWF0IjoxNjM3MDU4NzQ3LCJqdGkiOiIzNWJmOGI5ZS1kZmRmLTRmMWUtODE1NS1hYTEyMzlhY2ZlMmEifQ.gaEiqvZlngfjlsOnRulbXYm_ZLkzgESniJv87Ne1w28guzCKERBRqIRnj5MSPz4jEDVoBFUW7Q-hAEZpHAxARDVPh0B2AlXsVqnY7tw7ygSnFEbjgppHKUfJQBcpbYY9WjQ5uUm0YUYF8t7ov41ZWbEXTOgYykSU-ElTO9YqfRaQSEpOmCgPSA9o9EO_M2A3TXTdHg6zYBx6387zYVD5_ns11ouLHmYkeyHJ9DopCqOVbDDXYGux6fI1QM8E2OO0VWweWXInQWM8Po3-wsd0tdqtNvepltsQPcXdYu1J9x8qq1y21jXzc9x9Ly3Hc2VP4tNXj6ClgONLoKprRV2xcD_XuoE5yXR7v7qvmdBeXpCqxBB2vnbQTVyzJMjL-H0uO5yLiDMVrT3DCXk3SeHeR8jG9DKn6ClUpvdIr71tTztQQ-FZmqSvwd8Mj5wx0XJ-4KJcBmls5ijnyFHpj-G2O5HmlTlz2YRIMo7_ZEnJq7YBO8y16WOGAyz4_U9yRBEB2Y5bOxyoal7BC6IVJv1AKzjspBNLAjKWFR_Fj9e0wXEftj1vZD5qHCPBDsLhV0O1B6YCNNoivpw_tghAt5nWphRnTqY5mpfUQmB_XJR4boLeDcerfLheGipbaPKbKGUbU4ZsV2IT3dDk_bTBG8Ug7kWaU4C2UXGCKZnqoVkc2RI',
        'merchants_endpoint': 'https://api.kelkoogroup.net/publisher/shopping/v2/feeds/merchants',
    },
}